V2.0 dl file
makeopensource/Classic-RPG pull request #93
Opened 2022-10-06 00:39 UTC by emilkovacev

Proposed changes
-------------------------------------------
Closes #91 
Adds a new .dl file structure, 

Types of changes
-------------------------------------------
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

Checklist
-------------------------------------------
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [x] My changeset covers only what is described above (no extraneous changes)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged downstream

Further comments
-------------------------------------------
I chose to add a new parser (according to the specification of the issue) because the original one was getting a bit cluttered. I chose to keep both of the structures, and modify existing implementations to match the current version of crpg (maintaining legacy versioning is one of the strengths of this project). I also added a bunch of improvements to the regex parsing, so that newlines and spaces are a lot more forgiving, which they should be.

The one improvement I would like to make, is have a generic parser in parser/__init__.py that grabs the version number and passes it on to the appropriate functions instead of having to call the parser manually. Maybe I'll do it later. *Maybe.*

2022-10-06 05:01 UTC, Sploder12 requested changes
Really like these changes! I like where this project is headed.

Summary:
`crpg/parser/parser_v1.py` doesn't use regex split where it should.
`games/game-N.py` relative imports seem to be inconsistent.

various small naming suggestions

2022-10-06 05:01 UTC, Sploder12 commented on crpg/crpg.py
> +        connection_type_b: type = Connection
shortened "conn_type" is used above, perhaps change these to "conn_type_a/b" or switch above to "connection_type" to keep consistency.

2022-10-06 05:01 UTC, Sploder12 commented on crpg/setup.py
> +    while True:
trailing whitespace

2022-10-06 05:01 UTC, Sploder12 commented on crpg/parser/parser_v1.py
> +        node_mapping[n_alias] = obj
perhaps "n_id" or something similar would be better than "n_alias" here since it is a unique identifier?

2022-10-06 05:01 UTC, Sploder12 commented on crpg/parser/parser_v2.py
> +        node_mapping[alias] = obj
same as parser_v1.py comment. "id" or something similar may be better than "alias" here for a unique key/identifier.

2022-10-06 05:01 UTC, Sploder12 commented on crpg/parser/parser_v2.py
> +        game.add_node(obj)
should use game.add_starter_node for the starting node

2022-10-06 05:01 UTC, Sploder12 commented on crpg/parser/parser_v2.py
> +        node_b = node_mapping[node_b]
conversion of node_a/b from str to Node may be confusing. Perhaps add variables like "node_a/b_id" to reduce confusion.

2022-10-06 05:01 UTC, Sploder12 commented on games/game-3.py
> +sys.path.insert(0, "../crpg")
This has mixed results, it doesn't work for me when I run using VSCode's default debugging behavior. Works fine running from command line in the directory. Using `os`'s path module with generated absolute paths may be more portable. 

perhaps using import with relative paths may work better, but that has it's own issues.

2022-10-06 05:01 UTC, Sploder12 commented on crpg/parser/parser_v1.py
> +        nodes, connections = contents.split("\n+---\n+", maxsplit=1)
not a regex split so splits on
```
+---
+
``` 
which is not intended

2022-10-06 05:01 UTC, Sploder12 commented on crpg/builtin.py
> -        return str(self.from_node) + " \-> " + str(self.to_node)
great catch!

 (I just realized I put the comment with the wrong side of the diff, sorry!)

2022-10-06 19:18 UTC, emilkovacev commented on crpg/parser/parser_v2.py
> +        game.add_node(obj)
I'm deleting self.add_starter_node because of redundancy (I only ever need to call it once)

2022-10-06 20:58 UTC, emilkovacev commented on crpg/crpg.py
> +        connection_type_b: type = Connection
I changed conn -> connection

2022-10-06 20:58 UTC, emilkovacev commented on crpg/parser/parser_v1.py
> +        node_mapping[n_alias] = obj
switched n_alias -> node_id
And n_* -> node_*

2022-10-06 20:59 UTC, emilkovacev commented on crpg/parser/parser_v2.py
> +        node_b = node_mapping[node_b]
renamed variables appropriately

2022-10-06 20:59 UTC, emilkovacev commented on crpg/parser/parser_v1.py
> +        nodes, connections = contents.split("\n+---\n+", maxsplit=1)
fixed regex declaration

2022-10-06 21:18 UTC, emilkovacev commented on games/game-3.py
> +sys.path.insert(0, "../crpg")
I think I may try to add pytest to this in the future, so that we can run **actual tests** in the future. I'll make that an issue

2022-10-07 00:38 UTC, Sploder12 reviewed
Looks good besides some connectionections!

2022-10-07 00:38 UTC, Sploder12 commented on crpg/parser/parser_v1.py
> +            raise ConnectionError("Invalid .dl connectionection input")
connectionection -> connection
(same thing on line 65 in same file)

2022-10-07 00:38 UTC, Sploder12 commented on crpg/parser/parser_v2.py
> +        raise ConnectionError("Invalid .dl connectionection input")
connectionection -> connection

2022-10-07 00:38 UTC, Sploder12 commented on crpg/parser/parser_v2.py
> +# setup game with nodes and connectionections
more connectionections! (and line 100 of same file)

2022-10-07 00:38 UTC, Sploder12 commented on crpg/crpg.py
> +        from_node.add_connection(to_node, conn_type)
conn_type -> connection_type

2022-10-09 15:48 UTC, merged